In [4]:
import os
import pandas as pd
import numpy as np
Data = pd.read_csv('Toyota.csv',index_col=0,na_values=["??","????"])

In [5]:
Data.head(50)
Data.fillna(0.0,inplace=True)
Data.head(50)

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.0,46986.0,Diesel,90.0,1.0,0,2000,three,1165
1,13750,23.0,72937.0,Diesel,90.0,1.0,0,2000,3,1165
2,13950,24.0,41711.0,Diesel,90.0,0.0,0,2000,3,1165
3,14950,26.0,48000.0,Diesel,90.0,0.0,0,2000,3,1165
4,13750,30.0,38500.0,Diesel,90.0,0.0,0,2000,3,1170
5,12950,32.0,61000.0,Diesel,90.0,0.0,0,2000,3,1170
6,16900,27.0,0.0,Diesel,0.0,0.0,0,2000,3,1245
7,18600,30.0,75889.0,0.0,90.0,1.0,0,2000,3,1245
8,21500,27.0,19700.0,Petrol,192.0,0.0,0,1800,3,1185
9,12950,23.0,71138.0,Diesel,0.0,0.0,0,1900,3,1105
10,20950,25.0,31461.0,Petrol,192.0,0.0,0,1800,3,1185
11,19950,22.0,43610.0,Petrol,192.0,0.0,0,1800,3,1185
12,19600,25.0,32189.0,Petrol,192.0,0.0,0,1800,3,1185
13,21500,31.0,23000.0,Petrol,192.0,1.0,0,1800,3,1185
14,22500,32.0,34131.0,Petrol,192.0,1.0,0,1800,3,1185
15,22000,28.0,18739.0,Petrol,0.0,0.0,0,1800,3,1185
16,22750,30.0,34000.0,Petrol,192.0,1.0,0,1800,3,1185
17,17950,24.0,21716.0,Petrol,110.0,1.0,0,1600,3,1105
18,16750,24.0,25563.0,Petrol,110.0,0.0,0,1600,3,1065
19,16950,30.0,64359.0,Petrol,110.0,1.0,0,1600,3,1105
20,15950,30.0,67660.0,Petrol,110.0,1.0,0,1600,3,1105
21,16950,29.0,43905.0,0.0,110.0,0.0,1,1600,3,1170
22,15950,28.0,56349.0,Petrol,110.0,1.0,0,1600,3,1120
23,16950,28.0,32220.0,Petrol,110.0,1.0,0,1600,3,1120
24,16250,29.0,25813.0,Petrol,110.0,1.0,0,1600,3,1120
25,15950,25.0,28450.0,Petrol,110.0,1.0,0,1600,3,1120
26,17495,27.0,34545.0,0.0,110.0,1.0,0,1600,3,1120
27,15750,29.0,41415.0,Petrol,110.0,1.0,0,1600,3,1120
28,16950,28.0,44142.0,Petrol,110.0,0.0,0,1600,3,1120
29,17950,30.0,11090.0,0.0,110.0,0.0,0,1600,3,1120
30,12950,29.0,9750.0,Petrol,97.0,1.0,0,1400,3,1100
31,15750,22.0,35199.0,Petrol,97.0,1.0,0,1400,3,1100
32,15950,27.0,29510.0,Petrol,97.0,1.0,0,1400,3,1100
33,14950,0.0,32692.0,Petrol,97.0,1.0,0,1400,3,1100
34,15500,22.0,41000.0,Petrol,97.0,1.0,0,1400,3,1100
35,15750,26.0,43000.0,Petrol,97.0,0.0,0,1400,3,1100
36,15950,25.0,25000.0,Petrol,97.0,0.0,0,1400,3,1100
37,14950,23.0,10000.0,Petrol,97.0,1.0,0,1400,3,1100
38,15750,32.0,25329.0,Petrol,97.0,1.0,0,1400,3,1100
39,14750,27.0,27500.0,Petrol,97.0,0.0,0,1400,3,1100
40,13950,22.0,49059.0,Petrol,97.0,0.0,0,1400,3,1100
41,16750,27.0,44068.0,Petrol,97.0,1.0,0,1400,3,1100
42,13950,22.0,46961.0,Petrol,97.0,0.0,0,1400,3,1100
43,16950,27.0,110404.0,Diesel,90.0,0.0,0,2000,5,1255
44,16950,22.0,100250.0,0.0,90.0,0.0,0,2000,5,1255
45,19000,23.0,84000.0,Diesel,90.0,0.0,0,2000,5,1270
46,17950,27.0,79375.0,Diesel,90.0,1.0,0,2000,5,1255
47,15800,22.0,75048.0,Petrol,97.0,1.0,0,1400,5,1110
48,17950,22.0,72215.0,Diesel,90.0,1.0,0,2000,5,1255
49,21950,31.0,64982.0,Petrol,192.0,0.0,0,1800,5,1195

In [6]:
Data.info()
Data.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1436 non-null   float64
 2   KM         1436 non-null   float64
 3   FuelType   1436 non-null   object
 4   HP         1436 non-null   float64
 5   MetColor   1436 non-null   float64
 6   Automatic  1436 non-null   int64
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   object
 9   Weight     1436 non-null   int64
dtypes: float64(4), int64(4), object(2)
memory usage: 123.4+ KB

,Price,Age,KM,HP,MetColor,Automatic,CC,Weight
count,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.00000
mean,10730.824513,51.795265,67930.172702,101.054318,0.604457,0.055710,1566.827994,1072.45961
std,3626.964585,22.857014,37787.964148,16.126585,0.489137,0.229441,187.182436,52.64112
min,4350.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1300.000000,1000.00000
25%,8450.000000,40.000000,42702.500000,86.000000,0.000000,0.000000,1400.000000,1040.00000
50%,9900.000000,59.000000,63061.500000,110.000000,1.000000,0.000000,1600.000000,1070.00000
75%,11950.000000,68.000000,86916.000000,110.000000,1.000000,0.000000,1600.000000,1085.00000
max,32500.000000,80.000000,243000.000000,192.000000,1.000000,1.000000,2000.000000,1615.00000

In [7]:
Data['Automatic'] = Data['Automatic'].replace({0:'Non Automatic',1:'Automatic'})
Data.head(5)

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.0,46986.0,Diesel,90.0,1.0,Non Automatic,2000,three,1165
1,13750,23.0,72937.0,Diesel,90.0,1.0,Non Automatic,2000,3,1165
2,13950,24.0,41711.0,Diesel,90.0,0.0,Non Automatic,2000,3,1165
3,14950,26.0,48000.0,Diesel,90.0,0.0,Non Automatic,2000,3,1165
4,13750,30.0,38500.0,Diesel,90.0,0.0,Non Automatic,2000,3,1170

In [8]:
Data.rename(columns={'HP':'Horse Power'},inplace=True)
Data.head(5)

,Price,Age,KM,FuelType,Horse Power,MetColor,Automatic,CC,Doors,Weight
0,13500,23.0,46986.0,Diesel,90.0,1.0,Non Automatic,2000,three,1165
1,13750,23.0,72937.0,Diesel,90.0,1.0,Non Automatic,2000,3,1165
2,13950,24.0,41711.0,Diesel,90.0,0.0,Non Automatic,2000,3,1165
3,14950,26.0,48000.0,Diesel,90.0,0.0,Non Automatic,2000,3,1165
4,13750,30.0,38500.0,Diesel,90.0,0.0,Non Automatic,2000,3,1170

In [9]:
Data['Horse Power'] = Data['Horse Power'].astype('int')
Data.tail(5)

,Price,Age,KM,FuelType,Horse Power,MetColor,Automatic,CC,Doors,Weight
1431,7500,0.0,20544.0,Petrol,86,1.0,Non Automatic,1300,3,1025
1432,10845,72.0,0.0,Petrol,86,0.0,Non Automatic,1300,3,1015
1433,8500,0.0,17016.0,Petrol,86,0.0,Non Automatic,1300,3,1015
1434,7250,70.0,0.0,0.0,86,1.0,Non Automatic,1300,3,1015
1435,6950,76.0,1.0,Petrol,110,0.0,Non Automatic,1600,5,1114

In [10]:
Data['FuelType'] = Data['FuelType'].astype('str')
Data['FuelType'] =Data['FuelType'].replace({'0.0':'No Fuel Type'})
Data.head(5)
Data.tail(5)

,Price,Age,KM,FuelType,Horse Power,MetColor,Automatic,CC,Doors,Weight
1431,7500,0.0,20544.0,Petrol,86,1.0,Non Automatic,1300,3,1025
1432,10845,72.0,0.0,Petrol,86,0.0,Non Automatic,1300,3,1015
1433,8500,0.0,17016.0,Petrol,86,0.0,Non Automatic,1300,3,1015
1434,7250,70.0,0.0,No Fuel Type,86,1.0,Non Automatic,1300,3,1015
1435,6950,76.0,1.0,Petrol,110,0.0,Non Automatic,1600,5,1114

In [11]:
Data.rename(columns={'MetColor':'Metallic Color'},inplace=True)
Data['Metallic Color'] = Data['Metallic Color'].astype('str')
Data['Metallic Color'] = Data['Metallic Color'].replace({'0.0':'No Metallic Color','1.0':'Metallic Color'})
Data['Age'] = Data['Age'].astype('int')
Data['KM'] = Data['KM'].astype('str')+ ' Km'
# Data['KM'] = Data['KM'].astype('int')
Data['Weight'] = Data['Weight'].astype('int')
Data['Doors'] = Data['Doors'].replace({'three':3,'four':4,'five':5}) 
Data.head(50)
Data.tail(50)

,Price,Age,KM,FuelType,Horse Power,Metallic Color,Automatic,CC,Doors,Weight
1386,9750,69,52320.0 Km,Petrol,110,No Metallic Color,Non Automatic,1600,5,1070
1387,7450,78,52287.0 Km,Petrol,110,No Metallic Color,Non Automatic,1600,5,1114
1388,8750,75,52000.0 Km,Petrol,110,No Metallic Color,Non Automatic,1600,5,1075
1389,8750,69,52000.0 Km,Petrol,110,Metallic Color,Non Automatic,1600,3,1050
1390,8500,73,52000.0 Km,Petrol,110,Metallic Color,Automatic,1600,4,1065
1391,8950,70,51874.0 Km,Petrol,86,No Metallic Color,Non Automatic,1300,4,1000
1392,7500,79,49827.0 Km,Petrol,86,No Metallic Color,Non Automatic,1300,5,1035
1393,7250,69,49640.0 Km,No Fuel Type,110,Metallic Color,Non Automatic,1600,4,1035
1394,7450,80,49580.0 Km,No Fuel Type,110,Metallic Color,Non Automatic,1600,4,1035
1395,8750,76,49170.0 Km,No Fuel Type,86,No Metallic Color,Non Automatic,1300,3,1045
1396,9800,77,48838.0 Km,Petrol,110,No Metallic Color,Non Automatic,1600,3,1055
1397,7500,71,48576.0 Km,Petrol,86,Metallic Color,Non Automatic,1300,3,1015
1398,8950,75,48400.0 Km,Petrol,110,Metallic Color,Non Automatic,1600,5,1075
1399,8950,74,48242.0 Km,Petrol,86,Metallic Color,Non Automatic,1300,5,1035
1400,7450,70,47955.0 Km,Petrol,110,Metallic Color,Non Automatic,1600,5,1070
1401,8950,71,47633.0 Km,Petrol,110,Metallic Color,Non Automatic,1600,5,1075
1402,10500,0,47400.0 Km,Petrol,86,Metallic Color,Non Automatic,1300,5,1040
1403,7000,73,47360.0 Km,No Fuel Type,86,No Metallic Color,Non Automatic,1300,3,1010
1404,8500,77,45507.0 Km,Petrol,110,Metallic Color,Non Automatic,1600,3,1050
1405,7750,76,45410.0 Km,Petrol,86,Metallic Color,Non Automatic,1300,5,1035
1406,8950,70,44850.0 Km,Petrol,110,Metallic Color,Non Automatic,1600,3,1050
1407,8250,69,44826.0 Km,Petrol,110,No Metallic Color,Non Automatic,1600,5,1075
1408,9250,0,44444.0 Km,Petrol,110,Metallic Color,Non Automatic,1600,3,1050
1409,7900,75,43720.0 Km,Petrol,110,No Metallic Color,Non Automatic,1600,5,1070
1410,8500,78,43622.0 Km,Petrol,86,Metallic Color,Non Automatic,1300,4,1000
1411,7950,76,43532.0 Km,Petrol,110,No Metallic Color,Non Automatic,1600,5,1070
1412,9950,69,42800.0 Km,Petrol,110,Metallic Color,Non Automatic,1600,3,1050
1413,8750,74,42317.0 Km,Petrol,107,Metallic Color,Automatic,1600,5,1100
1414,7500,80,42186.0 Km,Petrol,110,Metallic Color,Non Automatic,1600,3,1050
1415,6950,72,42000.0 Km,Petrol,110,No Metallic Color,Non Automatic,1600,3,1050
1416,8950,0,40093.0 Km,Petrol,110,No Metallic Color,Non Automatic,1600,5,1114
1417,8750,79,39800.0 Km,Petrol,107,No Metallic Color,Automatic,1600,3,1080
1418,7750,73,39168.0 Km,Petrol,86,No Metallic Color,Non Automatic,1300,3,1015
1419,8450,75,38945.0 Km,Petrol,110,No Metallic Color,Non Automatic,1600,3,1050
1420,8150,76,36537.0 Km,No Fuel Type,110,No Metallic Color,Automatic,1600,4,1075
1421,8500,78,0.0 Km,Petrol,86,No Metallic Color,Automatic,1300,3,1045
1422,7600,0,36000.0 Km,No Fuel Type,110,Metallic Color,Non Automatic,1600,3,1050
1423,7950,80,35821.0 Km,Petrol,86,No Metallic Color,Automatic,1300,3,1015
1424,7750,73,34717.0 Km,Petrol,86,No Metallic Color,Non Automatic,1300,3,1015
1425,7950,80,0.0 Km,Petrol,86,Metallic Color,Non Automatic,1300,4,1000
1426,9950,78,30964.0 Km,Petrol,110,No Metallic Color,Automatic,1600,3,1080
1427,8950,0,29000.0 Km,Petrol,86,Metallic Color,Automatic,1300,3,1045
1428,8450,72,0.0 Km,Petrol,86,No Metallic Color,Non Automatic,1300,3,1015
1429,8950,78,24000.0 Km,Petrol,86,Metallic Color,Automatic,1300,5,1065
1430,8450,80,23000.0 Km,Petrol,86,No Metallic Color,Non Automatic,1300,3,1015
1431,7500,0,20544.0 Km,Petrol,86,Metallic Color,Non Automatic,1300,3,1025
1432,10845,72,0.0 Km,Petrol,86,No Metallic Color,Non Automatic,1300,3,1015
1433,8500,0,17016.0 Km,Petrol,86,No Metallic Color,Non Automatic,1300,3,1015
1434,7250,70,0.0 Km,No Fuel Type,86,Metallic Color,Non Automatic,1300,3,1015
1435,6950,76,1.0 Km,Petrol,110,No Metallic Color,Non Automatic,1600,5,1114

In [12]:
Data.to_excel('Toyota1.xlsx',index=False)

In [ ]:
j = ['Automatic','FuelType','Metallic Color','Doors','Weight','KM','Age','Horse Power','Price','CC']
for i in j:
    # it will give the frequency of each category
    a = pd.crosstab(index=Data[i],columns='count',dropna=True)
    print(a)

col_0          count
Automatic
Automatic         80
Non Automatic   1356
col_0         count
FuelType
CNG              15
Diesel          144
No Fuel Type    100
Petrol         1177
col_0              count
Metallic Color
Metallic Color       868
No Metallic Color    568
col_0  count
Doors
3          1
4          1
5          1
2          2
3        621
4        137
5        673
col_0   count
Weight
1000       17
1010        4
1015      117
1020        9
1025       70
1030       24
1035      106
1040       35
1045       31
1050      168
1055       43
1060       40
1065       51
1067        1
1070       89
1075      192
1078        1
1079        1
1080       47
1083        1
1084        1
1085       40
1090       10
1094        1
1095        4
1100       40
1103        1
1105       31
1109        1
1110       38
1114       10
1115       39
1119        3
1120       17
1121        1
1125        1
1130       29
1135       33
1140       16
1150        7
1155        2
1160        1
1165        8
1170        4
1172        1
1180        5
1185        9
1195        2
1205        4
1245        3
1255        7
1260        5
1265        1
1270        3
1275        2
1280        1
1320        3
1480        4
1615        1
col_0        count
KM
0.0 Km          15
1.0 Km           8
10000.0 Km       6
100123.0 Km      1
100192.0 Km      1
...            ...
99374.0 Km       1
99397.0 Km       1
99781.0 Km       1
99865.0 Km       1
99971.0 Km       1

[1256 rows x 1 columns]
col_0  count
Age
0        100
1          2
2          1
4          2
6          1
..       ...
76        26
77        36
78        41
79        28
80        52

[78 rows x 1 columns]
col_0        count
Horse Power
0                6
69              33
71               1
72              72
73               1
86             249
90              35
97             164
98               2
107             21
110            833
116              9
192             10
col_0  count
Price
4350       1
4400       1
4450       1
4750       1
5150       1
...      ...
24950      2
24990      1
31000      1
31275      1
32500      1

[236 rows x 1 columns]
col_0  count
CC
1300     248
1332       2
1398       2
1400     164
1587       4
1598       4
1600     846
1800      14
1900      30
1975       1
1995       2
2000     119